### ISSUE TITLE
panic: connection to mpd is severed: EOF

### ISSUE THREAD

**Issue by PreciseTroll** [natsukagami/mpd-mpris#25] opened 2021-05-21 17:41 UTC
Forgive my naivety. 

Today when mpd-mpris is running alongside mpd mpd will crash.

The output from mpd-mpris is

```
2021/05/21 12:28:54 command 'albumart' failed: No file exists
2021/05/21 12:28:54 mpd-mpris running
panic: connection to mpd is severed: EOF

goroutine 14 [running]:
github.com/natsukagami/mpd-mpris.(*Instance).transformErr(0xc000090060, 0x65f9a0, 0xc000495548, 0x0)
	/home/m/.cache/yay/mpd-mpris/src/mpd-mpris-0.3.0/errors.go:17 +0x2d9
github.com/natsukagami/mpd-mpris.(*Player).updateStatus(0xc000010108, 0xc00050ffa0)
	/home/m/.cache/yay/mpd-mpris/src/mpd-mpris-0.3.0/player.go:69 +0xc73
github.com/natsukagami/mpd-mpris.(*Player).properties.func1(0xc000010108)
	/home/m/.cache/yay/mpd-mpris/src/mpd-mpris-0.3.0/player.go:216 +0xb2
created by github.com/natsukagami/mpd-mpris.(*Player).properties
	/home/m/.cache/yay/mpd-mpris/src/mpd-mpris-0.3.0/player.go:212 +0x2c5
```

The error log from mpd shows:
`mpd: ../src/input/LastInputStream.cxx:42: void LastInputStream::OnCloseTimer(): Assertion is' failed.`

I apologize if this is unhelpful, or not in proper form (this is the first time I have ever reported an issue. Please let me know what else I can provide that may be helpful.
 Thank you for your time and attention.

**Comment by luevano** [comment] 2021-05-25 04:20
Hi, same here. I've been having the same problem for some days now after an update and I just recently decided to stop mpd-mpris service and now my mpd works. It was stopping after exactly 20 seconds.

The error logs are the same as OP.

**Comment by natsukagami** [comment] 2021-05-26 02:05
Thanks for the reports. Let me investigate, this is the first time I've seen this. That said, I haven't been using mpd lately.

**Comment by natsukagami** [comment] 2021-05-27 05:31
@luevano @PreciseTroll it seems to be a bug introduced in 0.22.7 of mpd (https://github.com/MusicPlayerDaemon/MPD/issues/1165). It is fixed in 0.22.8, please update mpd and confirm!

**Comment by lahwaacz** [comment] 2021-05-27 07:33
Hi, I can confirm this. Thanks for figuring it out!

**Comment by natsukagami** [comment] 2021-05-27 08:14
Ok, closing issue! If the problem persists, feel free to re-open.

**Closed by natsukagami** 2021-05-27 08:14 UTC
